name: Run Code

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes

jobs:
  run_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run code
        run: |
          python bot.py
